### PR TITLE
Allow specifying the sizes of vertices and consider that when laying out nodes

### LINKED ISSUE #7: Allow specifying the sizes of nodes
Today, AFAIK the only way to control the distance between nodes is through vertex spacing. This is a fixed amount of spacing between each node. Unfortunately this doesn't allow nodes to account for their size.

For example, I want each node to hold a string which can sometimes be fairly long. This means I either need to allow nodes to overlap which looks really bad, or I need to use a comically large vertex spacing, which makes parts of the graph that are small harder to read. 

Ideally the crate would allow me to give it the size of each node and it would use that to decide where to put the nodes so they don't overlap.

### PR DESCRIPTION
**Pull request by andriyDev**
Fixes #7.

> [!WARNING]
> This PR depends on #13, #16, and #17. As those evolve, I will keep this PR in sync and once the dependent PRs are merged, I will rebase this PR to remove the squash commit.

## Solution

Previously, when placing blocks and calculating class shifts, we would just shift the x coordinate by the vertex spacing (or the dummy size if applicable). Now we instead compute the width of the whole block (as the maximum of the vertex widths in the block), and then shift x coordinates by the block widths between the centers of the blocks.

This also simplified how we handle dummy vertex sizes, since we just treat dummy vertices like any other vertex. The width of the block is all that matters.

Note the previous implementation laid graphs out such that deeper nodes would be higher up. This PR changes that so that deeper nodes are lower down. You can easily mimic the old behavior by just negating the y coordinate yourself.

## Examples

The following examples all use a vertex spacing of 10.

### Before

This graph is literally incomprehensible. That's because the vertices don't consider their size. This means vertices are allowed to overlap and they do.

image

### After

image

image

image

### CODE REVIEW

**Comment by andriyDev** [comment]
Another thing I realized: currently this PR starts out nodes at (0, 0). Since this is the center of the node, node corners can actually start in negative coordinates. I'm not sure how much we care about this case, but it might be nice to shift nodes so their corners are all positive when laid out. The naive implementation of this could result in nodes starting with a margin from the origin of half the vertex spacing. This could in fact be desirable.

**Comment by dolezvo1** [comment]
I'm not sure if adding the sizing function as an mandatory argument to the `from_graph` function is the best course of action. Did you consider that someone might want to use the sizing function with the `from_edges`? Would it be possible to move it to the `Config`?

**Comment by dolezvo1** [comment]
I'm also not sure adding the `svg` dependency is a good idea. Formatting a string is generally not something you should need a library for.

**Comment by andriyDev** [comment]
> I'm not sure if adding the sizing function as an mandatory argument to the `from_graph` function is the best course of action. Did you consider that someone might want to use the sizing function with the `from_edges`? Would it be possible to move it to the `Config`?

I would argue that sizing of vertices is not a configuration property: it's a property of the vertices themself. I'd expect a lot of the time with `from_graph` the size will be just a field in the vertex storing the size. Alternatively, imagine you're using a text library to compute the size of the text of a vertex as it's size. Maybe there's some constants you can add to it, but primarily it's "here's how you get the size", rather then picking a size. 

In addition, since the type of vertices is chosen by the user (either it's a u32 for `from_vertex_and_edges`, or a generic V for `from_graph`) this would mean the config would have to be generic over the vertex type, which isn't great. 

> I'm also not sure adding the `svg` dependency is a good idea. Formatting a string is generally not something you should need a library for.

I don't feel bad about this since it's only a dev dependency and the code only exists in an example. Our priority for the example should be to show how you could render the graph in a simple way, not how to format SVG text.

**Comment by andriyDev** [comment]
One thing I also forgot to mention: we could also make from_edges support a sizing function by setting the vertex size after conversion to a graph if that's desirable. I initially didn't because I figured if you wanted fine-grained control of the vertices, you would use one of the other functions.

**Comment by dolezvo1** [comment]
> I would argue that sizing of vertices is not a configuration property: it's a property of the vertices themself.

I would have to disagree. Size is definitely a function of the vertex, but you may have a need for displaying one graph in multiple ways.

> In addition, since the type of vertices is chosen by the user (either it's a u32 for from_vertex_and_edges, or a generic V for from_graph) this would mean the config would have to be generic over the vertex type, which isn't great.

I don't believe that's true. See my original PR.

**Comment by andriyDev** [comment]
> I would have to disagree. Size is definitely a function of the vertex, but you may have a need for displaying one graph in multiple ways.

That's a fair point. But in that case, you can't share a `Config` between those calls anyway.

Since I've refactored the code out of being a builder, this argument is *mostly* organizational. It's mostly just the difference between putting the function in the config vs directly in the function call. Except for the next point...

> I don't believe that's true. See my original PR.

Your original PR had the sizing function as `&dyn Fn(NodeIndex) -> (f64, f64)`. That doesn't work because for `from_vertices_and_edges` there's no `NodeIndex`s in sight! The key type there is wrong. It's not clear how to convert from a `NodeIndex` into the vertex ID. Ideally you'd just have access to the value (which your PR does for `from_graph`),

It also means you have to do a "double lookup", since we're iterating through the graph to set the sizes, but then the vertex sizing function has to lookup in that graph based on the key.

Instead while we're iterating through the graph, we should just be able to pass the correct key or value type for the kind of operation we're doing (`from_graph`, `from_vertices_and_edges`). This is what my PR is doing.

**Comment by dolezvo1** [comment]
> That's a fair point. But in that case, you can't share a Config between those calls anyway.

Yeah, I hope I didn't imply that. The point I was trying to make is that I think the sizing function should not be a mandatory argument to the `from_graph` function, and I think the best way to do that would be to have the function be a part of the `Config`. 

> The key type there is wrong. It's not clear how to convert from a NodeIndex into the vertex ID.

That is true, but the `NodeIndex` for `StableDiGraph` is just a wrapper around `u32`. I would think there would be some way to work with that.

> It also means you have to do a "double lookup", since we're iterating through the graph to set the sizes, but then the vertex sizing function has to lookup in that graph based on the key.

I get what you mean, but I assume the lookup is just array indexation, is it not?

**Comment by dolezvo1** [comment]
I've been thinking about it real hard, and I think you're right. Semantically it doesn't make sense to have the sizing function in the config if it is only used in the `from_graph` function and ignored afterwards.

**Comment by paddison** [comment]
IMHO the size of the vertex should always be a property of the vertex itself and not of the configuration. And providing a sizing function as part of the `from_graph` api gives enough freedom to the user to modify it without too much of an overhead.

**Pull request merged**
