### PR TITLE
Added option to specify node sizes

### LINKED ISSUE #7: Allow specifying the sizes of nodes
Today, AFAIK the only way to control the distance between nodes is through vertex spacing. This is a fixed amount of spacing between each node. Unfortunately this doesn't allow nodes to account for their size.

For example, I want each node to hold a string which can sometimes be fairly long. This means I either need to allow nodes to overlap which looks really bad, or I need to use a comically large vertex spacing, which makes parts of the graph that are small harder to read. 

Ideally the crate would allow me to give it the size of each node and it would use that to decide where to put the nodes so they don't overlap.

### PR DESCRIPTION
**Pull request by dolezvo1**
Fixes #7 ?

### CODE REVIEW

**Comment by andriyDev** [comment]
I tried playing around with this the `from_graph` example and made this:

image

This is with decreasing the node heights to 15.0, and a vertex_spacing of 1 (note a vertex spacing of 0 is completely broken, it might be worth checking that it is at least 1). So it looks like we're not considering the size of a node.

In addition, I tried running the visualization through the HEAD state (with a vertex spacing of 100) and got this:
image

So it seems we're not taking into consideration the children nodes to decide the X coordinates of parents!

**Comment by dolezvo1** [comment]
Yeah, that all tracks. Both of these issues are symptoms of x axis being adjusted after the main layouting algorithm is completed. As I said, I will look into that.

**Comment by dolezvo1** [comment]
I think I managed to fix it, it was much simpler than anticipated.

**Comment by andriyDev** [comment]
This fix still doesn't quite work. Here's an example where I made one of the nodes just absurdly long: 

image

There's no reason for Jerry and Morty to be so far from Person.

**Comment by dolezvo1** [comment]
Yeah, that's true. I will try to look into that, but honestly I'm starting to think this algorithm maybe just doesn't work well when the vertices are not dimensionless.

**Comment by andriyDev** [comment]
@dolezvo1 I pulled out parts of this PR into separate PRs: #16 (this makes #8 obsolete), and #13. I added you as a co-author though since these are somewhat repackaging your commits. I would appreciate a review of these (but no pressure of course).

Note in #16 I've intentionally chosen not to create `to_svg` and instead just made it part of the example. I don't think we should be providing a way to render the the resulting layout - there's a bunch of ways and I don't think this crate has any business with it (e.g., I prefer rectangles over ellipses, which with a `to_svg` option we might then need to support). Better to just leave that to the calling code (but an example is still useful!).

I haven't yet made time to read the [underlying paper](https://www.semanticscholar.org/paper/Fast-and-Simple-Horizontal-Coordinate-Assignment-Brandes-K%C3%B6pf/69cb129a8963b21775d6382d15b0b447b01eb1f8) for phase 3, but I suspect it will shed light on adding size to vertices. I don't think we can do it as a "post-processing" step - I think we need the `mod algorithm::p3_calculate_coordinates` to consider the vertex sizes.

**Comment by andriyDev** [comment]
I created a new PR #18. I was able to figure it out! I am very happy with the resulting graphs.

**Comment by dolezvo1** [comment]
That looks really nice, congrats! Do I close this MR?

**Comment by andriyDev** [comment]
I would say so, since we've seen how this approach can break. But I'm not the maintainer so... :P

**Pull request closed without merging**
